from pydantic import BaseModel, Field, field_validator
from typing import List, Optional
from datetime import datetime

class Message(BaseModel):
    role: str = Field(..., description="The role of the message sender. Either 'user' or 'assistant'.")
    content: str = Field(..., description="The literal text content of the message.")

    @field_validator('role')
    @classmethod
    def validate_role(cls, v: str) -> str:
        if v not in ('user', 'assistant'):
            raise ValueError("Role must be either 'user' or 'assistant'")
        return v


class ChatRequest(BaseModel):
    messages: List[Message] = Field(..., description="The chronologically ordered historical messages in the session.")

    @field_validator('messages')
    @classmethod
    def validate_messages_count(cls, v: List[Message]) -> List[Message]:
        if not v:
            raise ValueError("The message history array cannot be empty.")
        if len(v) > 8:
            raise ValueError("The conversation cannot exceed a maximum turn budget of 8 exchanges.")
        return v


class RecommendationItem(BaseModel):
    name: str = Field(..., description="The primary name of the assessment.")
    url: str = Field(..., description="The official catalog reference link for the product.")
    test_type: str = Field(..., description="The categorization code: K, P, A, or I.")


class ChatResponse(BaseModel):
    reply: str = Field(..., description="The natural language dialogue reply generated by the agent.")
    recommendations: List[RecommendationItem] = Field(
        default_factory=list,
        description="A list of 0 to 10 recommended assessment items."
    )
    end_of_conversation: bool = Field(
        default=False,
        description="A flag indicating if the recommender agent has finalized the campaign spec shortlist."
    )


class SessionSummary(BaseModel):
    id: str
    title: str
    status: str
    turn_count: int
    created_at: str
    updated_at: str
